// Generated by gencpp from file xyzpublisher/Kenkipos.msg
// DO NOT EDIT!


#ifndef XYZPUBLISHER_MESSAGE_KENKIPOS_H
#define XYZPUBLISHER_MESSAGE_KENKIPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xyzpublisher
{
template <class ContainerAllocator>
struct Kenkipos_
{
  typedef Kenkipos_<ContainerAllocator> Type;

  Kenkipos_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Kenkipos_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::xyzpublisher::Kenkipos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xyzpublisher::Kenkipos_<ContainerAllocator> const> ConstPtr;

}; // struct Kenkipos_

typedef ::xyzpublisher::Kenkipos_<std::allocator<void> > Kenkipos;

typedef boost::shared_ptr< ::xyzpublisher::Kenkipos > KenkiposPtr;
typedef boost::shared_ptr< ::xyzpublisher::Kenkipos const> KenkiposConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xyzpublisher::Kenkipos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xyzpublisher::Kenkipos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xyzpublisher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'xyzpublisher': ['/home/jiang/Desktop/bao/openvslam/ros/src/xyzpublisher/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xyzpublisher::Kenkipos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xyzpublisher::Kenkipos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xyzpublisher::Kenkipos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feb38048784c133ece3b9bddb7dd3f47";
  }

  static const char* value(const ::xyzpublisher::Kenkipos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfeb38048784c133eULL;
  static const uint64_t static_value2 = 0xce3b9bddb7dd3f47ULL;
};

template<class ContainerAllocator>
struct DataType< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xyzpublisher/Kenkipos";
  }

  static const char* value(const ::xyzpublisher::Kenkipos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::xyzpublisher::Kenkipos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kenkipos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xyzpublisher::Kenkipos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xyzpublisher::Kenkipos_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XYZPUBLISHER_MESSAGE_KENKIPOS_H
